name: 'PR description validator'
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  enforce:
    runs-on: ubuntu-latest

    steps:
      - uses: openmodelingfoundation/pr-description-enforcer@414b6ff0ee78a50486c93c5ff6e50a89cd29a190 # v1.3.2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
