name: Run htmltest over rendered content
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Build Hugo site in Docker Compose
        run: make render-site HUGO_CACHE_CONTAINER_DIR=/src/.hugo_cache RENDER_OUTPUT_DIR=/src/public

      - name: Run htmltest
        continue-on-error: true
        uses: wjdp/htmltest-action@670ec9b79a149d30f4f5122e20cea1dfe82f8276 # v0.13.0-rc1
        with:
          config: .htmltest.yml

      - name: Archive htmltest results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: htmltest-report
          path: tmp/.htmltest/
          retention-days: 5
