name: Run htmltest over rendered content
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Hugo site in Docker Compose
        run: make render-site HUGO_CACHE_CONTAINER_DIR=/src/.hugo_cache RENDER_OUTPUT_DIR=/src/public

      - name: Run htmltest
        continue-on-error: true
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml

      - name: Archive htmltest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmltest-report
          path: tmp/.htmltest/
          retention-days: 5
